# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :plugin_altool do
    altool(
        altool_username: ENV["FASTLANE_USER"],
        altool_password: ENV["FASTLANE_PASSWORD"],
        altool_app_type: "ios",
        altool_ipa_path: "./build/dummy.ipa",
        altool_output_format: "normal",
    )
  end
end
